name: Deploy Slidev to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: presentation/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./presentation

      - name: Build static assets
        run: npm run build
        working-directory: ./presentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: presentation/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
